org.gradle.caching=true
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
fabric.loom.multiProjectOptimisation=true

project.group=com.iamkaf.minisort
project.plugins=3.0-SNAPSHOT

mod.name=Minisort
mod.authors=iamkaf
mod.id=minisort
mod.license=PolyForm-Shield-1.0.0
mod.credits=
mod.description=Sorts storage containers and refills emptied hands from matching inventory stacks.

publish.dry-run=false
publish.curseforge.id=1730907
publish.modrinth.id=u6c6EQt9
publish.release-type=release
publish.game-versions=auto
dependencies.modrinth.required=amber,konfig
dependencies.curseforge.required=amber-lib,konfig
environments.client=required
environments.server=required

mixin.compat.common=JAVA_21
mixin.compat.fabric=JAVA_21
mixin.compat.forge=JAVA_21
mixin.compat.neoforge=JAVA_21
